-- UUID uzantısı
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users
CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role::text = ANY (ARRAY['ADMIN'::character varying, 'USER'::character varying, 'SYSTEM'::character varying]::text[]))
);

CREATE INDEX IF NOT EXISTS idx_email ON public.users (email);

-- Ticket
CREATE TABLE IF NOT EXISTS public.tickets
(
    id uuid NOT NULL,
    created_at_date timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    priority character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_date timestamp(6) without time zone NOT NULL,
    assigned_to_id uuid NOT NULL,
    created_by_id uuid NOT NULL,
    updated_by_id uuid,
    CONSTRAINT tickets_pkey PRIMARY KEY (id),
    CONSTRAINT fk_tickets_updated_by FOREIGN KEY (updated_by_id) REFERENCES public.users (id),
    CONSTRAINT fk_tickets_created_by FOREIGN KEY (created_by_id) REFERENCES public.users (id),
    CONSTRAINT fk_tickets_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES public.users (id),
    CONSTRAINT tickets_priority_check CHECK (priority::text = ANY (ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying]::text[])),
    CONSTRAINT tickets_status_check CHECK (status::text = ANY (ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying, 'REOPENED'::character varying, 'BACKLOG'::character varying]::text[]))
);

CREATE INDEX IF NOT EXISTS idx_assigned_to_id ON public.tickets (assigned_to_id);
CREATE INDEX IF NOT EXISTS idx_created_at ON public.tickets (created_at_date);
CREATE INDEX IF NOT EXISTS idx_created_by ON public.tickets (created_by_id);
CREATE INDEX IF NOT EXISTS idx_status_priority ON public.tickets (status, priority);

-- Refresh Token 
CREATE TABLE IF NOT EXISTS public.refresh_token
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    revoked boolean NOT NULL,
    token character varying(255) NOT NULL,
    user_agent character varying(255),
    user_id uuid NOT NULL,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES public.users (id)
);



-- Comments 
CREATE TABLE IF NOT EXISTS public.comments
(
    id uuid NOT NULL,
    content character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone,
    user_id uuid,
    ticket_id uuid,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets (id) ON DELETE CASCADE
);

-- Audit Logs 
CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at_date timestamp(6) without time zone NOT NULL,
    details character varying(255) NOT NULL,
    error_message character varying(255),
    operation character varying(255) NOT NULL,
    performed_by character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT audit_logs_status_check CHECK (status::text = ANY (ARRAY['SUCCESS'::character varying, 'FAILED'::character varying]::text[]))
);

CREATE INDEX IF NOT EXISTS idx_audit_created_at ON public.audit_logs (created_at_date);
CREATE INDEX IF NOT EXISTS idx_audit_performed_by ON public.audit_logs (performed_by);