spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ticket_management_db
    username: postgres 
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ticket-management
    security:
      jwt:
        secret: ${JWT_SECRET}
        jwt-expiration-in-ms: ${JWT_EXPIRATION}
        refresh-token-expiration-in-ms : ${REFRESH_TOKEN_EXPIRATION}
        
